package com.example.employeeservice.domain;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

@Data
@Document(collection = "Employee")
public class Employee {
    @Id
    private String objectId;    // auto generated by mongoDB
    private String id;
    private String userID;
    private String firstName;
    private String lastName;
    private String middleName;
    private String preferedName;
    private String email;
    private String cellPhone;
    private String alternatePhone;
    private String gender;
    private String ssn;
    private String dob;
    private String startDate;
    private String endDate;
    private String driverLicense;
    private String driverLicenseExpiration;
    private String houseID;
    private List<Contact> contact;
    private List<Address> address;
    private List<VisaStatus> visaStatus;
    private List<PersonalDocument> personalDocument;
}

