server:
  port: 8082

spring:
  application:
    name: housing-service
  mvc:
    servlet:
      path: /housing-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
  #    prefer-ip-address: true

