server:
  port: 8082  # Port where Housing Service runs

spring:
  application:
    name: housing-service  # This is the name that will be used to register the service with Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka Server
    register-with-eureka: true  # Ensure that the service registers with Eureka
    fetch-registry: true  # Fetch the registry information from Eureka
  instance:
    prefer-ip-address: true  # Register with IP address instead of hostname
